### ISSUE TITLE
Database Schema

### ISSUE THREAD

**Issue by ssoonmi** [dmonahan19/Full-Stack-Project#1]
`pins`
- ~A `pin` can be pinned to many `boards`, and `boards` can have many `pins`, so you should make a join table between `pins` and `boards` instead of having a `board_id` on `pins`~
-----------------------------
`boards`
- ~A `board` should not belong to a `pin`, so having the foreign key of `pin_id` on `boards` is not appropriate. See comment on `pins`~
------------------------------
`follows`
- [x] probably want to make `follows` polymorphic. Your `follows` feature should allow users to `follow` `boards`, not just other `users`. (Speak to/Slack me if you want to talk about this)
-------------------------------
`board-pins`
- [x] don't need this table anymore

Nice job!
If you don't think some of these suggestions are appropriate, please comment below!

**Comment by ssoonmi** [comment]
`board_pins` makes more sense as a name instead of `pinboards`

**Comment by ssoonmi** [comment]
`follows` table should still have an `id` as a primary key

**Comment by dmonahan19** [comment]
fixed these issues
