### ISSUE TITLE
Sample State

### ISSUE THREAD

**Issue by ssoonmi** [dmonahan19/Full-Stack-Project#2]
- Pinterest looks like they have a different message for a `pin` for each `user` who re`pin`ned it. 
   - I think you should have the `title` and the `description` live on the `board_pins` table because of this
   - we can talk about it tomorrow if you are confused about this!
   - you probably want to have a slice of state for just `board_pins` that will have the `title` and the `description` of a `pin` that a specific `user` has `pinned` to a specific `board`
   - it also looks like that even though a `pin` can be on different `boards` with a different number of `likes`, is this true?
---
- Saved `pins`
   - if a `user` can save a `pin` without it being on a `board`, you need to have a `saved_pins` table that relates a `pin` to a `user` that has it saved
---
`boards`
- [x] `boards` slice of state should have ~`following` and~ `followers` just like `users` 

Awesome job!
I think we need to sit down and talk about how Pinterest works exactly. I'll fiddle around with it more and discuss it with you tomorrow!

**Comment by dmonahan19** [comment]
You were right about being able to follow boards so I will had following and followers to my board slice of state. I don't think a pin can be saved without being on a board. I tried playing around with it and every time I saved a pin I had to save it to a board but it also end up in just my pins.

**Comment by dmonahan19** [comment]
fixed these issues
